name: No_Ops deployment

on:
  push:
    branches: '*'

concurrency:
  group: "no_ops"
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  NOOPS_ORGANISATION: ${{ vars.NOOPS_ORGANISATION }}
  NOOPS_API_GRAPHQL: ${{ vars.NOOPS_API_GRAPHQL }}
  NOOPS_API_TOKEN: ${{ secrets.NOOPS_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: getnoops/action-ops@v0.1
        with:
          tag: v0.3.1
      - run: |
          ops version
      - id: repository
        run: |
          ops container-repository get website website --format=env >> $GITHUB_OUTPUT
      - run: |
          ops container-repository login website website | docker login --username ${{steps.repository.Username}} --password-stdin ${{steps.repository.RepositoryUri}}
          docker build -t ${{steps.repository.RepositoryUri}}:${GITHUB_SHA::7} .
          docker push ${{steps.repository.RepositoryUri}}:${GITHUB_SHA::7}
      - run: |
          echo "Deployed to ${{steps.repository.RepositoryUri}}:${GITHUB_SHA::7} successfully!"
