name: No_Ops deployment

on:
  push:
    branches: '*'

concurrency:
  group: "no_ops"
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: getnoops/action-ops@v0.1
      - id: repository
        run: |
          ops container-registry get website website --format=json >> $GITHUB_OUTPUT
      - run: |
          ops container-registry login website website | docker login --username ${{steps.repository.username}} --password-stdin ${{steps.repository.repository_uri}}
          docker build -t ${{steps.repository.repository_uri}}:${GITHUB_SHA::7} .
          docker push ${{steps.repository.repository_uri}}:${GITHUB_SHA::7}
      - run: |
          echo "Deployed to ${{steps.repository.repository_uri}}:${GITHUB_SHA::7}"
