name: No_Ops deployment

on:
  push:
    branches: '*'

concurrency:
  group: "no_ops"
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  NOOPS_ORGANISATION: ${{ vars.NOOPS_ORGANISATION }}
  NOOPS_API_GRAPHQL: ${{ vars.NOOPS_API_GRAPHQL }}
  NOOPS_API_TOKEN: ${{ secrets.NOOPS_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: getnoops/action-ops@v0.1
        with:
          tag: v0.4.0
      - id: repository
        run: |
          ops this info --format=env >> $GITHUB_OUTPUT
      - id: build
        run: |
          ops container-repository login | docker login --username ${{steps.repository.outputs.RegistryUsername}} --password-stdin ${{steps.repository.outputs.RegistryUri}}
          docker build -t ${{steps.repository.outputs.Repositories_Website_RepositoryUri}}:${GITHUB_SHA::7} .
          docker push ${{steps.repository.outputs.Repositories_Website_RepositoryUri}}:${GITHUB_SHA::7}
          echo "Image_Tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - run: |
          echo $GITHUB_OUTPUT
      - run: |
          ops this update --deploy=dev --next --vars-file .env --vars-file $GITHUB_OUTPUT
        env:
          Repositories_Website_RepositoryUri: ${{steps.repository.outputs.Repositories_Website_RepositoryUri}}
          Image_Tag: ${{steps.build.outputs.Image_Tag}}
