name: No_Ops deployment

on:
  push:
    branches: '*'

concurrency:
  group: "no_ops"
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

env:
  NOOPS_ORGANISATION: ${{ vars.NOOPS_ORGANISATION }}
  NOOPS_API_GRAPHQL: ${{ vars.NOOPS_API_GRAPHQL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: getnoops/action-ops@v0.1
        with:
          tag: v0.2.1
      - run: |
          ops version
      - id: repository
        run: |
          ops container-repository get website website --token=${{ secrets.NOOPS_API_TOKEN }} --format=json >> $GITHUB_OUTPUT
      - run: |
          ops container-repository login website website --token=${{ secrets.NOOPS_API_TOKEN }} | docker login --username ${{steps.repository.username}} --password-stdin ${{steps.repository.repository_uri}}
          docker build -t ${{steps.repository.repository_uri}}:${GITHUB_SHA::7} .
          docker push ${{steps.repository.repository_uri}}:${GITHUB_SHA::7}
        env:
          NOOPS_API_TOKEN: ${{ secrets.NOOPS_API_TOKEN }}
      - run: |
          echo "Deployed to ${{steps.repository.repository_uri}}:${GITHUB_SHA::7} successfully!"
